import json
from collections import deque

from openai import OpenAI

from config import (
    LLM_API_KEY,
    LLM_BASE_URL,
    LLM_MODEL,
    MAX_STEPS,
)
from prompts import SYSTEM_PROMPT
from tools import TOOL_SCHEMAS, execute_tool


class CodingAgent:
    def __init__(self):
        client_args = {
            "api_key": LLM_API_KEY,
        }

        # 如果使用 OpenAI-compatible 第三方接口，则设置 base_url
        if LLM_BASE_URL:
            client_args["base_url"] = LLM_BASE_URL

        self.client = OpenAI(**client_args)

        # 保存最近三次工具调用，用于简单检测死循环
        self.recent_tool_calls = deque(maxlen=3)

    def call_model(self, messages):
        """
        Send current conversation history and tool definitions to the LLM.
        """

        response = self.client.chat.completions.create(
            model=LLM_MODEL,
            messages=messages,
            tools=TOOL_SCHEMAS,
            tool_choice="auto",
        )

        return response.choices[0].message

    def is_repeated_call(self, name, arguments):
        """
        Detect whether the model has issued the exact same tool call
        three consecutive times.
        """

        signature = json.dumps(
            {
                "name": name,
                "arguments": arguments,
            },
            sort_keys=True,
            ensure_ascii=False,
        )

        self.recent_tool_calls.append(signature)

        if len(self.recent_tool_calls) < 3:
            return False

        return len(set(self.recent_tool_calls)) == 1

    def run(self, task: str):
        """
        Main Agent Loop.

        User task
            ↓
        LLM
            ↓
        Tool Call
            ↓
        Local execution
            ↓
        Observation
            ↓
        LLM
            ↓
        ...
        """

        messages = [
            {
                "role": "system",
                "content": SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": task,
            },
        ]

        print()
        print("=" * 60)
        print("TASK")
        print("=" * 60)
        print(task)

        for step in range(1, MAX_STEPS + 1):
            print()
            print(f"[Step {step}/{MAX_STEPS}]")

            # -------------------------------------------------
            # 1. Call LLM
            # -------------------------------------------------

            try:
                assistant_message = self.call_model(messages)

            except Exception as exc:
                result = (
                    "Agent stopped because the LLM request failed:\n"
                    f"{type(exc).__name__}: {exc}"
                )

                print(result)
                return result

            # -------------------------------------------------
            # 2. Save assistant message into history
            # -------------------------------------------------

            serialized_message = {
                "role": "assistant",
                "content": assistant_message.content,
            }

            if assistant_message.tool_calls:
                serialized_message["tool_calls"] = []

                for call in assistant_message.tool_calls:
                    serialized_message["tool_calls"].append(
                        {
                            "id": call.id,
                            "type": call.type,
                            "function": {
                                "name": call.function.name,
                                "arguments": call.function.arguments,
                            },
                        }
                    )

            messages.append(serialized_message)

            # -------------------------------------------------
            # 3. No tool call = Agent finished
            # -------------------------------------------------

            if not assistant_message.tool_calls:
                final_answer = (
                    assistant_message.content
                    or "Task completed."
                )

                print()
                print("=" * 60)
                print("FINAL")
                print("=" * 60)
                print(final_answer)

                return final_answer

            # -------------------------------------------------
            # 4. Execute every requested tool
            # -------------------------------------------------

            for tool_call in assistant_message.tool_calls:
                name = tool_call.function.name

                # Parse JSON arguments generated by model
                try:
                    arguments = json.loads(
                        tool_call.function.arguments or "{}"
                    )

                except json.JSONDecodeError as exc:
                    result = (
                        "ToolError: model generated invalid JSON "
                        f"arguments: {exc}"
                    )

                    messages.append(
                        {
                            "role": "tool",
                            "tool_call_id": tool_call.id,
                            "content": result,
                        }
                    )

                    continue

                print(f"Tool: {name}")
                print(
                    "Args:",
                    json.dumps(
                        arguments,
                        ensure_ascii=False,
                    ),
                )

                # -------------------------------------------------
                # 5. Simple loop detection
                # -------------------------------------------------

                if self.is_repeated_call(name, arguments):
                    result = (
                        "ToolError: identical tool call repeated "
                        "three times. Reconsider your approach "
                        "instead of repeating the same action."
                    )

                else:
                    # ---------------------------------------------
                    # 6. Execute local tool
                    # ---------------------------------------------

                    result = execute_tool(
                        name,
                        arguments,
                    )

                print("Result:")

                # Terminal output only displays first 3000 characters
                # to avoid flooding the screen.
                print(result[:3000])

                if len(result) > 3000:
                    print("... [terminal output truncated]")

                # -------------------------------------------------
                # 7. Return tool result to LLM
                # -------------------------------------------------

                messages.append(
                    {
                        "role": "tool",
                        "tool_call_id": tool_call.id,
                        "content": result,
                    }
                )

        # -----------------------------------------------------
        # Maximum number of steps reached
        # -----------------------------------------------------

        final_answer = (
            f"Agent stopped after reaching MAX_STEPS={MAX_STEPS}. "
            "The task may be incomplete."
        )

        print(final_answer)

        return final_answer